security:
  enable_authenticator_manager: true
  password_hashers:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    jwt:
      lexik_jwt:
        class: App\Entity\User

  firewalls:
    login:
      pattern: ^/api/login
      provider: app_user_provider
      stateless: true
      json_login:
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
      pattern: ^/api
      stateless: true
      provider: jwt
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN
